// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvobjowbmbjvntlucjon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2b2Jqb3dibWJqdm50bHVjam9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODU1NjEsImV4cCI6MjA2NzI2MTU2MX0.j7azA4tjiUEFs_xehnSga6aTX-kB988qSu2BTz_Ynk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});